<<<<<<< HEAD
//app/lauout.js

import '../../src/app/page'; // Correct the import if necessary
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> e32bf1d49b3692b98b29be6ce942b82e72656f7f

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        <div className="main">
          <div className="gradient"></div>
          <main className="app">
            {children}
          </main>
        </div>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> e32bf1d49b3692b98b29be6ce942b82e72656f7f
      </body>
    </html>
  );
}
<<<<<<< HEAD

=======
>>>>>>> e32bf1d49b3692b98b29be6ce942b82e72656f7f
